---
- name: Download Synaptics repository keyring package
  ansible.builtin.get_url:
    url: "https://www.synaptics.com/sites/default/files/Ubuntu/pool/stable/main/all/synaptics-repository-keyring.deb"
    dest: "{{ tempdir }}/synaptics-repository-keyring.deb"
    mode: '0644'

- name: Install Synaptics repository keyring
  ansible.builtin.apt:
    deb: "{{ tempdir }}/synaptics-repository-keyring.deb"
    state: present

- name: Clean up keyring package
  ansible.builtin.file:
    path: "{{ tempdir }}/synaptics-repository-keyring.deb"
    state: absent
