---
- name: Configure Git user.email
  community.general.git_config:
    scope: global
    name: user.email
    value: "{{ git_user_email }}"
  environment: "{{ gui_session_environment }}"

- name: Configure Git user.name
  community.general.git_config:
    scope: global
    name: user.name
    value: "{{ git_user_name }}"
  environment: "{{ gui_session_environment }}"
