---
- name: Add GPG keys
  ansible.builtin.apt_key:
    url: "{{ item.key_url }}"
    state: present
  loop: "{{ applications }}"
  loop_control:
    label: "{{ item.name }}"

- name: Add repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: present
  loop: "{{ applications }}"
  loop_control:
    label: "{{ item.name }}"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
